/**
 * This file was generated by the Jeddict
 */
package py.com.angularjpa;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author Renato Pradebon
 */
@Entity
public class Entidade {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String nome;

    @ManyToMany(targetEntity = Lista.class)
    private List<Lista> listas;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public List<Lista> getListas() {
        return this.listas;
    }

    public void setListas(List<Lista> listas) {
        this.listas = listas;
    }

}